Refactoring.RewardChamber.Web/Models/ChestModel.cs
using Refactoring.RewardChamber.Core;

namespace Refactoring.RewardChamber.Web.Models
{
    public class ChestModel
    {
        public Chest Chest { get; set; }

        public bool IsOpen { get; set; }

        public bool IsSelected { get; set; }
    }
}

Refactoring.RewardChamber.Web/Models/ErrorViewModel.cs
using System;

namespace Refactoring.RewardChamber.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Refactoring.RewardChamber.Web/Models/RewardChamberModel.cs
using System.Collections.Generic;

namespace Refactoring.RewardChamber.Web.Models
{
    public class RewardChamberModel
    {
        public int SpinCount { get; set; }

        public int TotalScore { get; set; }

        public List<ChestModel> Chests { get; set; }
    }
}

Refactoring.RewardChamber.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Refactoring.RewardChamber.Web.Models;

namespace Refactoring.RewardChamber.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Refactoring.RewardChamber.Web/Controllers/RewardController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Refactoring.RewardChamber.Core;
using Refactoring.RewardChamber.Core.Generator;
using Refactoring.RewardChamber.Web.Models;

namespace Refactoring.RewardChamber.Web.Controllers
{
    public class RewardController : Controller
    {
        private static Chamber _chamber;
        private static int? _openedChest;

        [HttpPost]
        public ActionResult Start(int spinCount, int baseReward)
        {
            var builder = new ChamberBuilder()
                .SetSpins(spinCount)
                .SetChestCount(3)
                .SetBaseReward(baseReward, 580)
                .AddMultiplier(2, 100)
                .AddMultiplier(3, 70)
                .AddMultiplier(5, 50)
                .AddRandomMultiplier(0.5, 100)
                .AddRandomMultiplier(1, 50)
                .AddFreeSpin(1, 50)
                .SetEmptyScore(300);

            _chamber = builder.Build();

            return Spin();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = BuildModel();

            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Open(int chestNumber)
        {
            _chamber.Open(chestNumber);
            _openedChest = chestNumber;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Spin()
        {
            _chamber.Spin();
            _openedChest = null;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Complete()
        {
            return View("Result", BuildModel());
        }

        private RewardChamberModel BuildModel()
        {
            var model = new RewardChamberModel
            {
                SpinCount = _chamber?.SpinsLeft ?? 0,
                TotalScore = _chamber?.Score ?? 0,

                Chests = _chamber?.Chests.Select(c => new ChestModel
                {
                    Chest = c,
                    IsOpen = _openedChest.HasValue,
                    IsSelected = _chamber.Chests.IndexOf(c) == _openedChest
                }).ToList() ?? new List<ChestModel>()
            };

            return model;
        }
    }
}

Refactoring.RewardChamber.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Reward Chamber";
}
<img src="https://previews.123rf.com/images/aquir/aquir1808/aquir180803387/111827278-reward-sign-reward-paper-origami-speech-bubble-reward-tag-reward-banner.jpg"
     style="width: 100%;"/>

<br/>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" Action="@Url.Action("Start", "Reward")" method="post">
            <div class="form-group">
                <label class="col-sm-offset-3 col-sm-2 control-label">Spin Count:</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" value="10" name="spinCount"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-offset-3 col-sm-2 control-label">Base Reward:</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" value="100" name="baseReward"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-1">
                    <button type="submit" class="btn btn-primary">Start</button>
                </div>
            </div>
        </form>
    </div>
</div>

Refactoring.RewardChamber.Web/Views/Reward/Index.cshtml
@model RewardChamberModel

@{
    ViewBag.Title = "Reward Chamber";
    Layout = "_Layout";
}

<h2>Reward Chamber</h2>

<div class="row">
    <div class="col-sm-offset-8 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-body text-right">
                <div class="form-inline form-group-lg">
                    <div class="form-group">
                        <label>Spin Count:</label>
                        <span class="form-control-static">@Model.SpinCount</span>
                    </div>
                    <div class="form-group">
                        <label>Score:</label>
                        <span class="form-control-static">@Model.TotalScore</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 text-center">

        @for (var i = 0; i < Model.Chests.Count; i++)
        {
            var chest = Model.Chests[i];
            var chestClass = chest.IsOpen ? chest.Chest.Reward > 0 || chest.Chest.FreeSpins > 0 ? "chest-full" : "chest-empty" : "chest-closed";

            @if (chest.IsOpen)
            {
                <div class="chest-container @(chest.IsSelected ? "selected" : "")">
                    <div class="chest @chestClass">
                        <div class="reward">
                            @if (chest.Chest.Reward > 0 || chest.Chest.FreeSpins > 0)
                            {
                                if (chest.Chest.Reward > 0)
                                {
                                    <div>+@chest.Chest.Reward</div>
                                }
                                
                                if (chest.Chest.FreeSpins > 0)
                                {
                                    <div>+@chest.Chest.FreeSpins Free Spin(s)</div>
                                }
                            }
                            else
                            {
                                <span>Empty</span>
                            }
                        </div>
                    </div>
                </div>
            }
            else
            {
                <form action="@Url.Action("Open", new {chestNumber = i})" style="display: inline-block" method="POST">
                    <button type="submit" class="chest-container">
                        <div class="chest @chestClass"></div>
                    </button>
                </form>
            }
        }

    </div>
</div>

<div class="row">
    <div class="col-sm-12 text-center">
        @if (Model.SpinCount > 0 || Model.Chests.Any(c => !c.IsOpen))
        {
            <form action='@Url.Action("Spin")' method="POST">
                <button type="@(Model.Chests.Any(c => c.IsOpen) ? " submit" : "button")" class="btn btn-default btn-lg @(Model.Chests.Any(c => c.IsOpen) ? " btn-primary" : "disabled")">Spin</button>
            </form>
        }
        else
        {
            <form action="@Url.Action("Complete")" method="POST">
                <button type="submit" class="btn btn-default btn-lg">Complete</button>
            </form>
        }
    </div>
</div>

Refactoring.RewardChamber.Web/Views/Reward/Result.cshtml
@model RewardChamberModel

@{
    ViewBag.Title = "Reward Chamber";
    Layout = "_Layout";
}

<h2>Reward Chamber</h2>

<div class="row">
    <div class="col-sm-12">
        <div class="jumbotron">
            <h1>Reward: @Model.TotalScore</h1>
        </div>
    </div>
</div>

Refactoring.RewardChamber.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Reward Chamber</a>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Refactoring.RewardChamber.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>